receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:


connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [ 100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms, 500ms, 1000ms, 1400ms, 2000ms, 5s, 10s, 20s, 40s, 60s ]
    dimensions:
    - name: http.method
      default: GET
    - name: http.status_code
    - name: http.route
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
    metrics_flush_interval: 15s

exporters:
  debug:
    verbosity: normal
    sampling_initial: 5
    sampling_thereafter: 200

  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ spanmetrics, debug, otlp ]

    metrics:
      receivers: [ otlp, spanmetrics ]
      processors: [ batch ]
      exporters: [ prometheus, debug ]
