global:
  scrape_interval: 5s

scrape_configs:
- job_name: 'otel-collector'
  static_configs:
  - targets:
    - otel-collector:8889
  metrics_path: '/metrics'
  scrape_interval: 10s
- job_name: 'fastapi-app'
  static_configs:
  - targets:
    - fastapi-app:8000
  metrics_path: '/metrics/'
