services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      GF_FEATURE_TOGGLES_ENABLE: "timeSeriesTable"
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"  
      - "8889:8889" 
      - "4317:4317"  
      - "4318:4318"
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector
    environment:
      - OTEL_SERVICE_NAME=fastapi-app
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
volumes:
  grafana-storage:
